In [4]:
import pandas as pd
pd.set_option('max_columns', 100)
pd.set_option('max_rows', 100)
import numpy as np

In [5]:
train = pd.read_csv(r'./train.csv')
test = pd.read_csv(r'./test.csv')
submit = pd.read_csv(r'./submit.csv')

In [6]:
print(train.shape)
print(test.shape)
train.nunique()

(40000, 21)
(15000, 20)


id            40000
XINGBIE           3
CSNY            393
HYZK              4
ZHIYE             7
ZHICHEN           4
ZHIWU             2
XUELI             2
DWJJLX           28
DWSSHY           21
GRJCJS        12447
GRZHZT            5
GRZHYE        34927
GRZHSNJZYE    37759
GRZHDNGJYE    31580
GRYJCE        16045
DWYJCE        16045
DKFFE           545
DKYE          21359
DKLL              8
label             2
dtype: int64

In [7]:
# 先把训练集和测试集拼接起来,一起处理
data = pd.concat([train, test])
data.shape

(55000, 21)

In [8]:
import time
def timeConvert(x):
    year = time.strftime("%Y", time.localtime(x))
    age = 2020 -int(year)
    return age
data['age'] = data['CSNY'].apply(timeConvert)
data.drop('CSNY', axis=1, inplace=True)

In [9]:
data.dtypes

id             object
XINGBIE         int64
HYZK            int64
ZHIYE           int64
ZHICHEN         int64
ZHIWU           int64
XUELI           int64
DWJJLX          int64
DWSSHY          int64
GRJCJS        float64
GRZHZT          int64
GRZHYE        float64
GRZHSNJZYE    float64
GRZHDNGJYE    float64
GRYJCE        float64
DWYJCE        float64
DKFFE           int64
DKYE          float64
DKLL          float64
label         float64
age             int64
dtype: object

In [10]:
sparse_feat = ['XINGBIE', 'HYZK', 'ZHIYE', 'ZHICHEN', 'ZHIWU', 'XUELI', 'DWJJLX', 'DWSSHY', 'GRZHZT']
dense_feat = list(data.columns)
for item in sparse_feat:
    dense_feat.remove(item)
dense_feat.remove('id')
dense_feat.remove('label')
dense_feat

['GRJCJS',
 'GRZHYE',
 'GRZHSNJZYE',
 'GRZHDNGJYE',
 'GRYJCE',
 'DWYJCE',
 'DKFFE',
 'DKYE',
 'DKLL',
 'age']

In [11]:
from sklearn.preprocessing import LabelEncoder
for feat in dense_feat:
    encoder = LabelEncoder()
    data[sparse_feat] = data[sparse_feat].apply(encoder.fit_transform)

In [12]:
# 做归一化
data[dense_feat] = (data[dense_feat] - data[dense_feat].min()) / (data[dense_feat].max() - data[dense_feat].min())

In [13]:
data.head(10)

id  XINGBIE  HYZK  ZHIYE  ZHICHEN  ZHIWU  XUELI  DWJJLX  DWSSHY  \
0  train_0        1     3      6        3      0      1       9      12   
1  train_1        2     3      6        3      0      1       1       0   
2  train_2        1     3      6        3      0      1       9       9   
3  train_3        1     3      6        3      0      1       9       7   
4  train_4        2     3      6        3      0      1      27      14   
5  train_5        1     3      6        3      0      1       9      14   
6  train_6        1     3      6        3      0      1      11       2   
7  train_7        1     3      6        3      0      1       9       7   
8  train_8        2     3      6        3      0      1       9       9   
9  train_9        2     3      6        3      0      1       9      14   

     GRJCJS  GRZHZT    GRZHYE  GRZHSNJZYE  GRZHDNGJYE    GRYJCE    DWYJCE  \
0  0.073615       0  0.008151    0.001735    0.821980  0.043651  0.043651   
1  0.318249       0  0.048629    0.162919    0.822758  0.366342  0.366342   
2  0.736924       0  0.074204    0.042212    0.843771  0.798758  0.798758   
3  0.719450       0  0.304666    0.305884    0.826869  0.780711  0.780711   
4  0.094537       0  0.000000    0.033188    0.819249  0.052655  0.052655   
5  0.031383       0  0.025685    0.021993    0.821758  0.038216  0.038216   
6  0.504456       0  0.061706    0.036727    0.839186  0.370317  0.370317   
7  0.047423       0  0.004288    0.018969    0.822708  0.047879  0.047879   
8  0.435568       0  0.215787    0.160313    0.840128  0.487512  0.487512   
9  0.215924       0  0.004836    0.187253    0.820957  0.260659  0.260659   

      DKFFE      DKYE      DKLL  label       age  
0  0.477612  0.466942  0.324240    0.0  0.994860  
1  0.850746  0.904340  0.535464    0.0  0.997513  
2  0.402985  0.446387  0.324240    0.0  0.996352  
3  1.000000  0.911625  0.324240    0.0  0.998010  
4  0.402985  0.439850  0.324240    0.0  0.997347  
5  0.402985  0.453682  0.324240    0.0  0.997679  
6  0.402985  0.444519  0.324240    0.0  0.997347  
7  0.328358  0.196340  0.324240    0.0  0.994528  
8  0.850746  0.820365  0.535464    0.0  0.997015  
9  0.641791  0.431085  0.324240    0.0  0.997844

In [14]:
data.columns

Index(['id', 'XINGBIE', 'HYZK', 'ZHIYE', 'ZHICHEN', 'ZHIWU', 'XUELI', 'DWJJLX',
       'DWSSHY', 'GRJCJS', 'GRZHZT', 'GRZHYE', 'GRZHSNJZYE', 'GRZHDNGJYE',
       'GRYJCE', 'DWYJCE', 'DKFFE', 'DKYE', 'DKLL', 'label', 'age'],
      dtype='object')

In [15]:
# 调整列的排序
new_index = ['id'] + sparse_feat + dense_feat + ['label']
data = data.reindex(columns=new_index)

In [16]:
data.head(10)

id  XINGBIE  HYZK  ZHIYE  ZHICHEN  ZHIWU  XUELI  DWJJLX  DWSSHY  \
0  train_0        1     3      6        3      0      1       9      12   
1  train_1        2     3      6        3      0      1       1       0   
2  train_2        1     3      6        3      0      1       9       9   
3  train_3        1     3      6        3      0      1       9       7   
4  train_4        2     3      6        3      0      1      27      14   
5  train_5        1     3      6        3      0      1       9      14   
6  train_6        1     3      6        3      0      1      11       2   
7  train_7        1     3      6        3      0      1       9       7   
8  train_8        2     3      6        3      0      1       9       9   
9  train_9        2     3      6        3      0      1       9      14   

   GRZHZT    GRJCJS    GRZHYE  GRZHSNJZYE  GRZHDNGJYE    GRYJCE    DWYJCE  \
0       0  0.073615  0.008151    0.001735    0.821980  0.043651  0.043651   
1       0  0.318249  0.048629    0.162919    0.822758  0.366342  0.366342   
2       0  0.736924  0.074204    0.042212    0.843771  0.798758  0.798758   
3       0  0.719450  0.304666    0.305884    0.826869  0.780711  0.780711   
4       0  0.094537  0.000000    0.033188    0.819249  0.052655  0.052655   
5       0  0.031383  0.025685    0.021993    0.821758  0.038216  0.038216   
6       0  0.504456  0.061706    0.036727    0.839186  0.370317  0.370317   
7       0  0.047423  0.004288    0.018969    0.822708  0.047879  0.047879   
8       0  0.435568  0.215787    0.160313    0.840128  0.487512  0.487512   
9       0  0.215924  0.004836    0.187253    0.820957  0.260659  0.260659   

      DKFFE      DKYE      DKLL       age  label  
0  0.477612  0.466942  0.324240  0.994860    0.0  
1  0.850746  0.904340  0.535464  0.997513    0.0  
2  0.402985  0.446387  0.324240  0.996352    0.0  
3  1.000000  0.911625  0.324240  0.998010    0.0  
4  0.402985  0.439850  0.324240  0.997347    0.0  
5  0.402985  0.453682  0.324240  0.997679    0.0  
6  0.402985  0.444519  0.324240  0.997347    0.0  
7  0.328358  0.196340  0.324240  0.994528    0.0  
8  0.850746  0.820365  0.535464  0.997015    0.0  
9  0.641791  0.431085  0.324240  0.997844    0.0

In [17]:
data.shape

(55000, 21)

In [18]:
# 把处理好的数据表进行拆分, 得到训练集和测试集
transform_train = data.iloc[:40000, :]
transform_test = data.iloc[40000:, :-1]     #不需要label列
print(transform_test.shape)

(15000, 20)


In [19]:
transform_test.head(10)

id  XINGBIE  HYZK  ZHIYE  ZHICHEN  ZHIWU  XUELI  DWJJLX  DWSSHY  \
0  test_0        1     3      6        3      0      1      10      10   
1  test_1        1     3      6        3      0      1       9      11   
2  test_2        1     3      6        3      1      1       1      15   
3  test_3        2     3      6        3      0      1       9      10   
4  test_4        1     3      6        3      0      1       9       2   
5  test_5        1     3      6        3      0      1       9       0   
6  test_6        1     3      6        3      0      1       1      14   
7  test_7        1     3      6        3      0      1       9       7   
8  test_8        1     3      6        3      0      1       9      14   
9  test_9        1     3      6        3      0      1       9       2   

   GRZHZT    GRJCJS    GRZHYE  GRZHSNJZYE  GRZHDNGJYE    GRYJCE    DWYJCE  \
0       0  0.123983  0.046148    0.040408    0.822867  0.065327  0.065327   
1       0  0.034870  0.009679    0.005870    0.821299  0.026978  0.026978   
2       0  0.373956  0.140688    0.107450    0.822930  0.423878  0.423878   
3       0  0.169702  0.001496    0.001470    0.810555  0.176372  0.176372   
4       0  0.303332  0.110490    0.082646    0.846954  0.350936  0.350936   
5       0  0.251143  0.035444    0.018755    0.827171  0.170616  0.170616   
6       0  0.183534  0.002474    0.026400    0.820177  0.227206  0.227206   
7       0  0.031383  0.000261    0.000472    0.819931  0.025477  0.025477   
8       0  0.031383  0.000543    0.000197    0.820391  0.038216  0.038216   
9       0  0.216195  0.026367    0.039830    0.829043  0.216388  0.216388   

      DKFFE      DKYE      DKLL       age  
0  0.283582  0.000000  0.324240  0.997513  
1  0.552239  0.541149  0.324240  0.997015  
2  0.402985  0.444084  0.422447  1.000000  
3  0.691045  0.733928  0.535464  0.997347  
4  0.253731  0.218740  0.324240  0.999834  
5  0.402985  0.393419  0.324240  0.998010  
6  0.850746  0.833171  0.324240  0.996352  
7  0.588060  0.611464  0.324240  0.996684  
8  0.402985  0.205495  0.324240  0.998839  
9  0.462687  0.437615  0.324240  0.996684

In [20]:
# 存储处理好的数据
import pickle
with open(r'./train_T.pkl', 'wb') as f:
    pickle.dump(transform_train, f)
with open(r'./test_T.pkl', 'wb') as f:
    pickle.dump(transform_test, f)

In [21]:
# 存储数据集的信息, 构建input_dict字典
import json
input_dict = {'sparse': None, 'dense': None}
input_dict['dense'] = len(dense_feat)
input_dict['sparse'] = list(data[sparse_feat].nunique())
with open(r'./info.json', 'w') as f:
    json.dump(input_dict, f)
input_dict

{'sparse': [3, 4, 7, 4, 2, 2, 28, 21, 5], 'dense': 10}

In [100]:
# 进行欠采样对数据进行平衡
over_index = np.where(transform_train['label']==1)[0]
sample_index = np.random.choice(np.where(transform_train['label']==0)[0], int(len(over_index) * 1.2))
sample_index = set(sample_index)
sample_index = np.array(list(sample_index))
all_index = np.concatenate((over_index, sample_index), axis=0)
all_index = np.sort(all_index)
all_index
train_data = transform_train.iloc[all_index, :]

In [117]:
# 尝试使用LGBM
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(train_data.iloc[:, 1:20].values, train_data.iloc[:, 20].values, test_size=0.2)
print(y_train)
param = {'n_estimators': 10, 'learning_rate': 0.05, 'num_leaves': 31, 'boosting_type': 'gbdt'}
model = lgb.sklearn.LGBMClassifier(**param)
model.fit(X_train, y_train.astype(int))
y_predict = model.predict(X_test)
print(accuracy_score(y_test, y_predict))

[0. 1. 0. ... 0. 1. 1.]
0.8016877637130801


In [113]:
X_test.shape
y_predict.shape

(1185, 2)

In [118]:
from sklearn.metrics import recall_score, f1_score, roc_curve

print(recall_score(y_test, y_predict))
print(f1_score(y_test, y_predict))
fpr, tpr, thresholds = roc_curve(y_test, y_predict)
print(thresholds)
y_predict

0.7132216014897579
0.7652347652347652
[2 1 0]


array([0, 1, 0, ..., 0, 0, 0])

In [119]:
res = model.predict_proba(transform_test.iloc[:, 1:].values)[:, 1]
res.shape

(15000,)

In [120]:
import time
def submit(res):
    subimt_csv = pd.read_csv(r'./submit.csv')
    subimt_csv['label'] = res
    time_path = time.strftime("%Y%m%d%H%M", time.localtime()) + '.csv'
    subimt_csv.to_csv('../submission/' + time_path, index=False)
submit(res)

In [29]:
transform_train.describe()

XINGBIE          HYZK         ZHIYE       ZHICHEN         ZHIWU  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       1.361900      2.999275      5.995025      2.996175      0.000150   
std        0.480868      0.043296      0.138927      0.089781      0.012247   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        1.000000      3.000000      6.000000      3.000000      0.000000   
50%        1.000000      3.000000      6.000000      3.000000      0.000000   
75%        2.000000      3.000000      6.000000      3.000000      0.000000   
max        2.000000      3.000000      6.000000      3.000000      1.000000   

              XUELI       DWJJLX        DWSSHY        GRZHZT        GRJCJS  \
count  40000.000000  40000.00000  40000.000000  40000.000000  40000.000000   
mean       0.999850     10.18755      9.612775      0.005725      0.288317   
std        0.012247      8.29608      5.541372      0.100461      0.220428   
min        0.000000      0.00000      0.000000      0.000000      0.000000   
25%        1.000000      1.00000      6.000000      0.000000      0.122046   
50%        1.000000      9.00000     10.000000      0.000000      0.240256   
75%        1.000000     11.00000     14.000000      0.000000      0.390859   
max        1.000000     27.00000     20.000000      4.000000      1.000000   

             GRZHYE    GRZHSNJZYE    GRZHDNGJYE        GRYJCE        DWYJCE  \
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000   
mean       0.040346      0.046374      0.818727      0.293727      0.293727   
std        0.055101      0.061694      0.027161      0.230043      0.230043   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.004518      0.008479      0.817158      0.109678      0.109678   
50%        0.022676      0.026982      0.821758      0.246934      0.246934   
75%        0.052822      0.059461      0.827488      0.401837      0.401837   
max        1.000000      0.962916      1.000000      1.000000      1.000000   

              DKFFE          DKYE          DKLL           age         label  
count  40000.000000  40000.000000  40000.000000  40000.000000  40000.000000  
mean       0.522649      0.473605      0.371070      0.997713      0.068925  
std        0.224880      0.234903      0.114349      0.005122      0.253330  
min        0.000000      0.000000      0.000000      0.000000      0.000000  
25%        0.402985      0.333847      0.324240      0.996850      0.000000  
50%        0.402985      0.442963      0.324240      0.997513      0.000000  
75%        0.701493      0.608749      0.324240      0.998508      0.000000  
max        1.000000      1.000000      1.000000      1.000000      1.000000

发现问题: 样本分布极为不平衡. label为1也即逾期的样本占总样本的大约6%.
解决方案: 打算先进行欠采样尝试, 如果效果不好再使用过采样


学习如何把训练集和测试集的每个特征分布画在一张图中进行对比